#!/usr/bin/env python

# Simple web server for testing tmda-cgi

import sys
import os.path
import re
import CGIHTTPServer
from CGIHTTPServer import CGIHTTPRequestHandler

(directory, script) = os.path.split(sys.argv[0])
tmda_cgi_dir = os.path.abspath(os.path.join(directory, '..'))

if not os.path.exists(os.path.join(tmda_cgi_dir, 'configure.ini')):
    print >> sys.stderr, 'configure.ini not found. Run configure first.'
    sys.exit(1)

class RequestHandler(CGIHTTPRequestHandler):
    _path_matcher = re.compile(r'^.*/simple-server/www/display/(?P<tail>.*)$')
    def translate_path(self, path):
        # Special case for display/ paths. If the path doesn't exist in the
        # current directory, translate it to the display/ dir in tmda-cgi.
        translated = CGIHTTPRequestHandler.translate_path(self, path)
        if not os.path.exists(translated):
            m = self._path_matcher.match(translated)
            if m:
                return os.path.join(tmda_cgi_dir, 'display', m.group('tail'))

        return translated

os.chdir(os.path.join(tmda_cgi_dir, 'simple-server', 'www'))

CGIHTTPServer.test(HandlerClass=RequestHandler)
