#!/usr/bin/env python

import compileall
import os
import sys

tmda_tld = os.path.dirname(sys.argv[0])

# Recursively byte-compile all .py files even if the timestamps are up to date.
compileall.compile_dir(tmda_tld,force=1)
