.\" Hey, EMACS: -*- nroff -*-
.TH TMDA-CHECK-ADDRESS 1 "2010-01-24" TMDA "TMDA Programs"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\" **********************************************************************
.SH NAME
tmda\-check\-address \- validate a tagged e-mail address
.\" **********************************************************************
.SH SYNOPSIS
.SY tmda\-check\-address
.RI [ options ]
.I address
.RI [ sender ]
.YS
.\" **********************************************************************
.SH DESCRIPTION
.B \%tmda\-check\-address
checks a tagged (dated, keyword, or sender style only) e-mail address.
The required
.I address
argument is the address you want to check.
The optional
.I sender
is the sender address to verify if checking a sender-style address.
.\" **********************************************************************
.SH OPTIONS
.TP
.BI "\-c " file
.TQ
.BI \-\-config\-file= file
Specify a configuration file other than
.BR \(ti/.tmda/config .
.TP
.B \-l
.TQ
.B \-\-localtime
Display dates in the local time zone instead of UTC.
.TP
.B \-V
Show full TMDA version information and exit.
.TP
.B \-\-version
Show program's version number and exit.
.TP
.B \-h
.TQ
.B \-\-help
Show this help message and exit.
.\" **********************************************************************
.\".SH SEE ALSO
.\" **********************************************************************
.SH AUTHOR
TMDA was written by
.MT jason@mastaler.com
Jason R. Mastaler
.ME .
.PP
This manual page was adapted from the program
.B \%\-\-help
output by
.MT kevin\-opensource@omegacrash.net
Kevin Goodsell
.ME ,
for the Debian project (but may be used by others).
