#!/bin/sh

# Run tmda-ofmipd in the foreground with debug output, using options
# from /etc/default/tmda-ofmipd.

DAEMONUSER=tofmipd

. /etc/default/tmda-ofmipd

start-stop-daemon --start --exec /usr/bin/tmda-ofmipd --chuid $DAEMONUSER \
    -- -f -d $DAEMON_OPTS
