.\" Hey, EMACS: -*- nroff -*-
.\" Include www macros (see groff_www(7))
.mso www.tmac
.
.TH TMDA-KEYGEN 1 "2009-03-25" TMDA "TMDA Programs"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\" **********************************************************************
.SH NAME
tmda-keygen \- generate a unique 160-bit hex key
.\" **********************************************************************
.SH SYNOPSIS
.B tmda-keygen
.RI [ options ]
.\" **********************************************************************
.SH DESCRIPTION
.B tmda-keygen
generates the unique key for the
.I ~/.tmda/crypt_key
file.
A new TMDA user needs to do this once.
.\" **********************************************************************
.SH OPTIONS
.TP
.BI -d\  device ,\ --device= device
Draw random numbers from a random data source device other than
.IR /dev/urandom .
.TP
.B -b, --batch
Output only the CRYPT_KEY.
.TP
.B -V
Show full TMDA version information and exit.
.TP
.B --version
Show program's version number and exit.
.TP
.B -h, --help
Show this help message and exit.
.\" **********************************************************************
.\".SH SEE ALSO
.\" **********************************************************************
.SH AUTHOR
TMDA was written by
.MTO jason@mastaler.com "Jason R. Mastaler" .
.PP
This manual page was adapted from the program
.B --help
output by
.MTO kevin-opensource@omegacrash.net "Kevin Goodsell" ,
for the Debian project (but may be used by others).
