.\" Hey, EMACS: -*- nroff -*-
.\" Include www macros (see groff_www(7))
.mso www.tmac
.
.TH TMDA-OFMIPD 1 "2009-03-26" TMDA "TMDA Programs"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\" **********************************************************************
.SH NAME
tmda-ofmipd \- proxy to tag outgoing SMTP email
.\" **********************************************************************
.SH SYNOPSIS
.B tmda-ofmipd
.RI [ options ]
.\" **********************************************************************
.SH DESCRIPTION
.B tmda-ofmipd
is an authenticated ofmip proxy for TMDA that allows you to `tag' your
mail client's outgoing mail through SMTP.  For more information,
including setup and usage instructions, see
.URL http://\:wiki.\:tmda.\:net/TmdaOfmipdHowto "the TMDA wiki" .
.\" **********************************************************************
.SH OPTIONS
.TP
.B -V
Show full TMDA version information and exit.
.TP
.B --version
Show program's version number and exit.
.TP
.B -h, --help
Show this help message and exit.
.SS General
.TP
.B -d, --debug
Turn on debugging prints.
.TP
.B -L, --log
Turn on logging prints.
This option logs everything that
.B -d
logs, except for the raw SMTP protocol data.
Hence, it is useful if you want to leave logging enabled permanently, but
don't want your logs bloated with AUTH data and/or the content of large
attachments.
.TP
.B -b, --background
Detach and run in the background (default).
.TP
.B -f, --foreground
Don't detach; run in the foreground.
.TP
.BI -u\  username ,\ --username= username
The username that this program should run under.
The default is to run as the user who starts the program unless that is
root, in which case an attempt to seteuid user `tofmipd' will be made.
Use this option to override these defaults.
.TP
.BI -c\  dir ,\ --configdir= dir
.RI ` dir '
is the base directory to search for the authenticated user's TMDA
configuration file in.
This might be useful if you wish to maintain TMDA files outside the
user's home directory.
.RI ` username/config '
will be appended to form the path; e.g,
.RB ` -c\ /var/tmda '
will have
.B tmda-ofmipd
search for
.RI ` /var/tmda/bobby/config '.
If this option is not used,
.RI ` ~user/.tmda/config '
will be assumed, but see the
.B --vhome-script
option for qmail virtual domain users.
.SS Connection
.TP
.BI -p\  host:port ,\ --proxyport= host:port
The
.I host:port
to listen for incoming connections on.
The default is FQDN:8025 (i.e, port 8025 on the fully qualified domain
name for the local host).
Use
.RI ` 0.0.0.0:port '
to listen on all available interfaces.
.TP
.BI -C\  num ,\ --connections= num
Do not handle more than
.I num
simultaneous connections.
If there are
.I num
active connections, defer acceptance of new connections until one
finishes.
.I num
must be a positive integer.
The default is 20.
.TP
.B -1, --one-session
Don't bind to a port and accept new connections.
Process a single SMTP session on stdin (used both for input & output).
This is useful when started from tcpserver or stunnel.
.TP
.B -P, --pure-proxy
Proxy the message straight through to the mail transport system unaltered
if the user's TMDA config file is missing.
The
.I /usr/sbin/sendmail
program on the system is used to inject the message.
You can override this by setting $TMDA_SENDMAIL_PROGRAM in the
environment.
This option might be useful when serving a mixed environment of TMDA and
non-TMDA users.
.TP
.BI -t\  /path/to/script ,\ --throttle-script= /path/to/script
Full pathname of a script which can meter how much mail any user sends.
The script is passed a login name whenever a user tries to send mail.
If the script returns a 0, the message is allowed.
For any other value, the message is rejected.
.TP
.B --ssl
Enable SSL encryption.
This mode immediately initiates the SSL/TLS protocol as soon as a
connection is made.
This mode is not support for the STARTTLS command.
This configuration is typically run on port 465 (smtps).
.TP
.BI --tls= mode
Enable TLS mode.
Valid modes are
.BR optional ,\  localoptional \ and\  on .
With this option enabled, the STARTTLS SMTP command may be used to
upgrade the plain-text connection to SSL/TLS.
This protects the safety of plain-text authentication methods, and
message content.
This is typically run on port 587 (submission).
The different options have the following effect:
.TS
center, box;
l | l | l
lfB | l | l.
	AUTH allowed before STARTTLS?	AUTH after STARTTLS?
_
optional	yes	yes
localoptional	connections from localhost only	yes
on	no	yes
.TE
.TP
.BI --ssl-cert= /path/to/file
Location of the SSL/TLS certificate key file.
.TP
.BI --ssl-key= /path/to/file
Location of the SSL/TLS private key file.
.SS Authentication
.TP
.BI -R\  proto :// host [: port ][/ dn ],\ --remoteauth= proto :// host \
[: port ][/ dn ]
Protocol and host to check username and password.
.I proto
can be one of the following:
.RB ` imap '
(IMAP4 server),
.RB ` imaps '
(IMAP4 server over SSL),
.RB ` pop3 '
(POP3 server),
.RB ` apop '
(POP3 server with APOP authentication),
.RB ` ldap '
(LDAP server).
Optional
.I :port
defaults to the standard port for the specified protocol (143 for imap,
993 for imaps, 110 for pop3/apop, and 389 for ldap).
.I /dn
is mandatory for ldap and should contain a '%s' identifying the
username.
.IP ""
Examples:
.RS 1.5i
-R imaps://myimapserver.net
.br
-R pop3://mypopserver.net:2110
.br
-R ldap://example.com/cn=%s,dc=host,dc=com
.RE
.TP
.BI -A\  program ,\ --authprog= program
A checkpassword compatible command used to check username/password.
.IP ""
Examples:
.RS 1.5i
-A "/usr/sbin/checkpassword-pam -s id -- /bin/true"
.br
-A "/usr/local/vpopmail/bin/vchkpw /usr/bin/true"
.RE
.IP ""
The program must be able to receive the username/password pair on
descriptor 3 and in the following format: `username\\0password\\0'.
Any program claiming to be checkpassword-compatible should be able to do
this.
If you can tell the program to accept input on another descriptor, such
as stdin, don't.
It won't work, because TMDA follows
.URL http://\:cr.yp.to\:/checkpwd\:/interface.html "the standard"
exactly.
Also, checkpassword-type programs expect to find the name of another
program to run on their command line.
For
.BR tmda-ofmipd 's
purpose,
.I /bin/true
is perfectly fine.
Note the position of the quotes in the Examples, which cause the the
whole string following the
.B -A
to be passed as a single argument.
.TP
.BI -a\  file ,\ --authfile= file
Path to the file holding authentication information for this proxy.
Default location is
.I /etc/tofmipd
if running as root/tofmipd, otherwise
.IR ~user/.tmda/tofmipd .
Use this option to override these defaults.
.TP
.B -F, --fallback
When used with
.B -R
or
.BR -A ,
fallback to authenticate against the authfile if remote authentication
fails.
Note: this flag has no effect on
.B -R
to
.B -A
fallback.
If you specify both
.B -R
and
.B -A
methods, then authprog will be tried after remoteauth has failed.
.SS Virtual Domains
.TP
.BI -S\  /path/to/script ,\ --vhome-script= /path/to/script
Full pathname of a script that prints a virtual email user's home
directory on standard output.
.B tmda-ofmipd
will read that and use it to build the path to the user's config file
instead of
.RI ` ~user/.tmda '.
The script must take two arguments, the user name and the domain, on its
command line.
This option is for use only with the VPopMail and VMailMgr add-ons to
qmail.
See the
.I /usr/share/tmda/scripts
directory for sample scripts.
.TP
.BI -v\  /path/to/file ,\ --vdomains-path= /path/to/file
Full pathname to qmail's virtualdomains file.
The default is
.IR /var/qmail/control/virtualdomains .
This is also tmda-ofmipd's default, so you normally won't need to set
this parameter.
If you have installed qmail somewhere other than
.IR /var/qmail ,
you will need to set this so
.B tmda-ofmipd
can find the virtualdomains file.
NOTE: This is only used when you have a qmail installation with virtual
domains using the VMailMgr add-on.
It implies that you will also set the
.RB ` --vhome-script '
option above.
.\" **********************************************************************
.\".SH SEE ALSO
.\" **********************************************************************
.SH AUTHOR
TMDA was written by
.MTO jason@mastaler.com "Jason R. Mastaler" .
.PP
This manual page was adapted from the program
.B --help
output by
.MTO kevin-opensource@omegacrash.net "Kevin Goodsell" ,
for the Debian project (but may be used by others).
